### ISSUE TITLE
Filters stay highlightet even if not using it currently

### ISSUE THREAD

**Issue by Jonth4th** [lunauii/terragear#1]
![Screenshot 2023-05-26 1790446](https://github.com/lunauii/terragear/assets/134719303/90a4d704-9fd4-4906-a4ba-e4fc81acb4c4)

the filters change colour every time i click on them, i think only the current selected should only be black

**Comment by lunauii** [comment]
Yup, will fix this soon 🙏

**Comment by lunauii** [comment]
fixed in v0.3.0
